# Generated by Django 5.1.3 on 2024-12-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('idproduktu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField()),
                ('producent', models.CharField(max_length=100)),
                ('sciezka_do_zdjecia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('uzytkownikid', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rola', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('klientid', models.AutoField(primary_key=True, serialize=False)),
                ('adres', models.TextField()),
                ('nrTelefonu', models.CharField(max_length=15)),
                ('dataRejestracji', models.DateTimeField(auto_now_add=True)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('punkty_lojalnosciowe', models.IntegerField(default=0)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.uzytkownik')),
            ],
        ),
    ]
