# Generated by Django 5.1.3 on 2024-12-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0002_remove_klient_klientid_remove_produkt_idproduktu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
