# Generated by Django 5.1.3 on 2024-12-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0003_alter_klient_id_alter_produkt_id_alter_uzytkownik_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaKoszyka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.koszyk')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
            ],
        ),
    ]
