# Generated by Django 5.1.3 on 2025-01-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0004_koszyk_pozycjakoszyka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='OCZEKUJĄCE', max_length=50)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.zamowienie')),
            ],
        ),
    ]
