# Generated by Django 5.1.3 on 2025-01-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0005_zamowienie_pozycjazamowienia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPrzedmiotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaSpersonalizowana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('powod', models.CharField(max_length=255)),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.klient')),
                ('idPrzedmiotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
            ],
        ),
    ]
