# Generated by Django 5.1.3 on 2025-01-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0006_oferta_ofertaspersonalizowana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('nowi_klienci', 'Nowi Klienci'), ('starzy_klienci', 'Starzy Klienci'), ('wieloryby', 'Wieloryby'), ('nieaktywni', 'Nieaktywni')], max_length=50, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaKlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='DjangoProject.grupa')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupy', to='DjangoProject.klient')),
            ],
            options={
                'unique_together': {('klient', 'grupa')},
            },
        ),
    ]
