# Generated by Django 5.1.3 on 2025-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0007_grupa_grupaklient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='nazwa',
            field=models.CharField(choices=[('nowi_klienci', 'Nowi Klienci'), ('starzy_klienci', 'Starzy Klienci'), ('nieaktywni', 'Nieaktywni')], max_length=50, unique=True),
        ),
    ]
