# Generated by Django 5.1.3 on 2025-01-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0008_alter_grupa_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
                ('condition_type', models.CharField(choices=[('bought_product', 'Klienci, którzy kupili przedmiot'), ('spent_amount_last_days', 'Klienci, którzy wydali określoną kwotę w ostatnich dniach'), ('spent_amount_total', 'Klienci, którzy wydali określoną kwotę całkowicie'), ('account_age', 'Klienci, których konto istnieje przez określony czas')], max_length=50)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('produkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DjangoProject.produkt')),
            ],
        ),
    ]
