# Generated by Django 5.1.3 on 2025-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0009_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
