# Generated by Django 5.1.3 on 2025-01-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0012_grupa_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaOfertGrupowych',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.grupa')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
            ],
        ),
    ]
