# Generated by Django 5.1.3 on 2025-01-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0013_historiaofertgrupowych'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField(blank=True, null=True)),
                ('warunek', models.JSONField(blank=True, null=True)),
                ('czas_trwania', models.PositiveIntegerField()),
                ('aktywowana', models.BooleanField(default=False)),
                ('grupy', models.ManyToManyField(to='DjangoProject.grupa')),
            ],
        ),
        migrations.CreateModel(
            name='KampaniaProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kampania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.kampania')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.produkt')),
            ],
        ),
    ]
