# Generated by Django 5.1.3 on 2025-01-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0014_kampania_kampaniaprodukt'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampania',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
