# Generated by Django 5.1.3 on 2025-01-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0015_kampania_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kampania',
            name='is_cancelled',
        ),
    ]
