# Generated by Django 5.1.3 on 2025-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0016_remove_kampania_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('kolor', models.CharField(default='#ffffff', max_length=7)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
