# Generated by Django 5.1.3 on 2025-01-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0017_notatka'),
    ]

    operations = [
        migrations.CreateModel(
            name='NazwaKampanii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=255)),
                ('kampania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nazwa', to='DjangoProject.kampania')),
            ],
        ),
    ]
